Netlist(Freeze)
Netlist(Clear)
Netlist(Add,unnamed_net60,Q100-3)
Netlist(Add,unnamed_net60,R100-1)
Netlist(Add,unnamed_net59,Q100-2)
Netlist(Add,unnamed_net59,R101-1)
Netlist(Add,unnamed_net58,Q100-1)
Netlist(Add,unnamed_net58,CONN7-1)
Netlist(Add,unnamed_net57,LED2-3)
Netlist(Add,unnamed_net57,S3-2)
Netlist(Add,unnamed_net57,Q2-3)
Netlist(Add,unnamed_net56,R42-2)
Netlist(Add,unnamed_net56,U6-8)
Netlist(Add,unnamed_net55,R42-1)
Netlist(Add,unnamed_net55,U6-1)
Netlist(Add,unnamed_net54,S1-5)
Netlist(Add,unnamed_net54,S1-3)
Netlist(Add,unnamed_net54,CONN1-1)
Netlist(Add,unnamed_net53,S1-6)
Netlist(Add,unnamed_net53,S1-2)
Netlist(Add,unnamed_net53,CONN1-2)
Netlist(Add,unnamed_net52,TP10-1)
Netlist(Add,unnamed_net52,S3-1)
Netlist(Add,unnamed_net52,U5-4)
Netlist(Add,unnamed_net51,R27-1)
Netlist(Add,unnamed_net51,R28-1)
Netlist(Add,unnamed_net51,U5-7)
Netlist(Add,unnamed_net50,C16-2)
Netlist(Add,unnamed_net50,R28-2)
Netlist(Add,unnamed_net50,U5-2)
Netlist(Add,unnamed_net50,U5-6)
Netlist(Add,unnamed_net49,C19-2)
Netlist(Add,unnamed_net49,U5-5)
Netlist(Add,unnamed_net48,BUZ2-1)
Netlist(Add,unnamed_net48,U5-3)
Netlist(Add,unnamed_net47,LED2-4)
Netlist(Add,unnamed_net47,R26-2)
Netlist(Add,unnamed_net46,D2-1)
Netlist(Add,unnamed_net46,Q2-2)
Netlist(Add,unnamed_net46,LED2-6)
Netlist(Add,unnamed_net46,LED2-2)
Netlist(Add,unnamed_net46,R25-2)
Netlist(Add,unnamed_net45,CONN3-2)
Netlist(Add,unnamed_net45,R24-1)
Netlist(Add,unnamed_net45,R23-1)
Netlist(Add,unnamed_net44,S2-1)
Netlist(Add,unnamed_net44,R23-2)
Netlist(Add,unnamed_net43,U3-6)
Netlist(Add,unnamed_net43,TP9-1)
Netlist(Add,unnamed_net43,S2-4)
Netlist(Add,unnamed_net43,R41-3)
Netlist(Add,unnamed_net42,R40-1)
Netlist(Add,unnamed_net42,R21-1)
Netlist(Add,unnamed_net41,LED2-1)
Netlist(Add,unnamed_net41,R22-1)
Netlist(Add,unnamed_net40,R19-1)
Netlist(Add,unnamed_net40,U3-7)
Netlist(Add,unnamed_net40,R20-1)
Netlist(Add,unnamed_net39,U3-1)
Netlist(Add,unnamed_net39,R22-2)
Netlist(Add,unnamed_net39,R20-2)
Netlist(Add,unnamed_net38,LED2-5)
Netlist(Add,unnamed_net38,R18-1)
Netlist(Add,unnamed_net37,S2-2)
Netlist(Add,unnamed_net37,TP8-1)
Netlist(Add,unnamed_net37,R21-3)
Netlist(Add,unnamed_net37,R16-2)
Netlist(Add,unnamed_net36,R18-2)
Netlist(Add,unnamed_net36,U3-14)
Netlist(Add,unnamed_net36,R17-1)
Netlist(Add,unnamed_net35,R16-1)
Netlist(Add,unnamed_net35,U3-9)
Netlist(Add,unnamed_net35,R17-2)
Netlist(Add,Scaled_EKG_Out,CONN2-1)
Netlist(Add,Scaled_EKG_Out,TP7-1)
Netlist(Add,Scaled_EKG_Out,R14-1)
Netlist(Add,Scaled_EKG_Out,R15-2)
Netlist(Add,EKG_Out,S2-3)
Netlist(Add,EKG_Out,U3-8)
Netlist(Add,EKG_Out,R19-2)
Netlist(Add,EKG_Out,TP6-1)
Netlist(Add,EKG_Out,R14-2)
Netlist(Add,EKG_Out,U4-6)
Netlist(Add,EKG_Out,U4-2)
Netlist(Add,EKG_Out,C6-1)
Netlist(Add,unnamed_net34,U1-2)
Netlist(Add,unnamed_net34,R5-1)
Netlist(Add,unnamed_net33,U4-3)
Netlist(Add,unnamed_net33,C7-2)
Netlist(Add,unnamed_net33,R13-1)
Netlist(Add,unnamed_net32,C6-2)
Netlist(Add,unnamed_net32,R13-2)
Netlist(Add,unnamed_net32,R12-1)
Netlist(Add,unnamed_net31,C5-1)
Netlist(Add,unnamed_net31,R12-2)
Netlist(Add,unnamed_net31,R11-1)
Netlist(Add,unnamed_net30,C4-2)
Netlist(Add,unnamed_net30,R10-2)
Netlist(Add,unnamed_net30,TP5-1)
Netlist(Add,unnamed_net30,U1-1)
Netlist(Add,unnamed_net30,R11-2)
Netlist(Add,unnamed_net29,R101-2)
Netlist(Add,unnamed_net29,U1-3)
Netlist(Add,unnamed_net29,BUZ1-2)
Netlist(Add,unnamed_net29,LED1-2)
Netlist(Add,unnamed_net29,R9-2)
Netlist(Add,unnamed_net28,BUZ1-1)
Netlist(Add,unnamed_net28,R9-3)
Netlist(Add,unnamed_net27,LED1-1)
Netlist(Add,unnamed_net27,R8-1)
Netlist(Add,unnamed_net26,C1-2)
Netlist(Add,unnamed_net26,U1-5)
Netlist(Add,unnamed_net26,R3-1)
Netlist(Add,unnamed_net25,R2-2)
Netlist(Add,unnamed_net25,U1-7)
Netlist(Add,unnamed_net25,R1-2)
Netlist(Add,unnamed_net24,U2-4)
Netlist(Add,unnamed_net24,C2-2)
Netlist(Add,unnamed_net23,U1-6)
Netlist(Add,unnamed_net23,TP4-1)
Netlist(Add,unnamed_net23,R4-1)
Netlist(Add,unnamed_net23,C2-1)
Netlist(Add,unnamed_net22,U2-14)
Netlist(Add,unnamed_net22,C3-2)
Netlist(Add,unnamed_net21,R7-1)
Netlist(Add,unnamed_net21,U2-15)
Netlist(Add,unnamed_net21,C3-1)
Netlist(Add,unnamed_net20,U2-3)
Netlist(Add,unnamed_net20,U2-2)
Netlist(Add,unnamed_net20,R6-1)
Netlist(Add,unnamed_net19,Q1-1)
Netlist(Add,unnamed_net19,R30-1)
Netlist(Add,unnamed_net18,Q1-3)
Netlist(Add,unnamed_net18,TP3-1)
Netlist(Add,unnamed_net18,U2-1)
Netlist(Add,unnamed_net18,R29-1)
Netlist(Add,+5V,C101-1)
Netlist(Add,+5V,U2-16)
Netlist(Add,+5V,TP17-1)
Netlist(Add,+5V,VREG1-1)
Netlist(Add,+5V,C17-1)
Netlist(Add,+5V,CONN3-1)
Netlist(Add,+5V,R41-1)
Netlist(Add,+5V,R1-1)
Netlist(Add,+5V,R4-2)
Netlist(Add,+5V,R7-2)
Netlist(Add,+5V,R6-2)
Netlist(Add,+5V,R29-2)
Netlist(Add,+5V,R33-2)
Netlist(Add,+5V,D1-1)
Netlist(Add,+5V,R32-2)
Netlist(Add,unnamed_net17,TP2-1)
Netlist(Add,unnamed_net17,R30-2)
Netlist(Add,unnamed_net17,U3-2)
Netlist(Add,unnamed_net17,R31-1)
Netlist(Add,unnamed_net16,U3-5)
Netlist(Add,unnamed_net16,R32-1)
Netlist(Add,unnamed_net16,R31-2)
Netlist(Add,unnamed_net15,U3-4)
Netlist(Add,unnamed_net15,R33-1)
Netlist(Add,unnamed_net15,D1-2)
Netlist(Add,unnamed_net15,C11-1)
Netlist(Add,unnamed_net14,S1-1)
Netlist(Add,unnamed_net14,R39-1)
Netlist(Add,unnamed_net13,U6-3)
Netlist(Add,unnamed_net13,C15-2)
Netlist(Add,unnamed_net13,R36-2)
Netlist(Add,unnamed_net12,R38-2)
Netlist(Add,unnamed_net12,R36-1)
Netlist(Add,unnamed_net12,C13-2)
Netlist(Add,unnamed_net11,S1-4)
Netlist(Add,unnamed_net11,R39-2)
Netlist(Add,unnamed_net11,C13-1)
Netlist(Add,unnamed_net10,U6-2)
Netlist(Add,unnamed_net10,C14-2)
Netlist(Add,unnamed_net10,R35-2)
Netlist(Add,unnamed_net9,R37-2)
Netlist(Add,unnamed_net9,R35-1)
Netlist(Add,unnamed_net9,C12-2)
Netlist(Add,unnamed_net8,R39-3)
Netlist(Add,unnamed_net8,C12-1)
Netlist(Add,unnamed_net7,U6-6)
Netlist(Add,unnamed_net7,TP1-1)
Netlist(Add,unnamed_net7,R34-1)
Netlist(Add,unnamed_net6,C11-2)
Netlist(Add,unnamed_net6,R34-2)
Netlist(Add,unnamed_net5,CONN5-9)
Netlist(Add,unnamed_net5,CONN4-9)
Netlist(Add,unnamed_net4,CONN5-7)
Netlist(Add,unnamed_net4,CONN4-7)
Netlist(Add,+15V,R100-2)
Netlist(Add,+15V,VREG1-3)
Netlist(Add,+15V,U4-7)
Netlist(Add,+15V,C18-1)
Netlist(Add,+15V,U1-8)
Netlist(Add,+15V,C102-1)
Netlist(Add,+15V,U6-7)
Netlist(Add,+15V,R40-2)
Netlist(Add,+15V,R27-2)
Netlist(Add,+15V,C8-1)
Netlist(Add,+15V,U5-8)
Netlist(Add,+15V,R26-1)
Netlist(Add,+15V,R25-1)
Netlist(Add,+15V,R9-1)
Netlist(Add,+15V,R8-2)
Netlist(Add,+15V,R3-2)
Netlist(Add,+15V,C9-2)
Netlist(Add,+15V,U3-3)
Netlist(Add,+15V,C110-1)
Netlist(Add,+15V,C108-1)
Netlist(Add,+15V,C106-1)
Netlist(Add,+15V,C104-1)
Netlist(Add,+15V,TP15-1)
Netlist(Add,+15V,C1001-2)
Netlist(Add,+15V,CONN5-5)
Netlist(Add,+15V,CONN4-5)
Netlist(Add,unnamed_net3,CONN5-3)
Netlist(Add,unnamed_net3,CONN4-3)
Netlist(Add,Chassis,CONN2-4)
Netlist(Add,Chassis,CONN2-3)
Netlist(Add,Chassis,CONN1-4)
Netlist(Add,Chassis,S1-7)
Netlist(Add,Chassis,CONN1-3)
Netlist(Add,Chassis,S3-8)
Netlist(Add,Chassis,S1-8)
Netlist(Add,Chassis,S3-7)
Netlist(Add,Chassis,TP11-1)
Netlist(Add,Chassis,CONN5-1)
Netlist(Add,Chassis,CONN4-1)
Netlist(Add,unnamed_net2,CONN5-8)
Netlist(Add,unnamed_net2,CONN4-8)
Netlist(Add,unnamed_net1,CONN5-6)
Netlist(Add,unnamed_net1,CONN4-6)
Netlist(Add,-15V,C103-1)
Netlist(Add,-15V,U4-4)
Netlist(Add,-15V,U6-4)
Netlist(Add,-15V,C10-1)
Netlist(Add,-15V,U3-12)
Netlist(Add,-15V,U3-11)
Netlist(Add,-15V,C111-2)
Netlist(Add,-15V,C109-2)
Netlist(Add,-15V,C107-2)
Netlist(Add,-15V,C105-2)
Netlist(Add,-15V,TP16-1)
Netlist(Add,-15V,C1000-1)
Netlist(Add,-15V,CONN5-4)
Netlist(Add,-15V,CONN4-4)
Netlist(Add,GND,C103-2)
Netlist(Add,GND,C102-2)
Netlist(Add,GND,C101-2)
Netlist(Add,GND,CONN7-2)
Netlist(Add,GND,C19-1)
Netlist(Add,GND,C18-2)
Netlist(Add,GND,S3-3)
Netlist(Add,GND,U2-8)
Netlist(Add,GND,Q1-2)
Netlist(Add,GND,Q2-1)
Netlist(Add,GND,U2-11)
Netlist(Add,GND,U2-9)
Netlist(Add,GND,VREG1-2)
Netlist(Add,GND,C17-2)
Netlist(Add,GND,C7-1)
Netlist(Add,GND,C5-2)
Netlist(Add,GND,C4-1)
Netlist(Add,GND,U1-4)
Netlist(Add,GND,U6-5)
Netlist(Add,GND,D2-2)
Netlist(Add,GND,C14-1)
Netlist(Add,GND,C15-1)
Netlist(Add,GND,CONN2-2)
Netlist(Add,GND,BUZ2-2)
Netlist(Add,GND,C16-1)
Netlist(Add,GND,C1-1)
Netlist(Add,GND,C8-2)
Netlist(Add,GND,C10-2)
Netlist(Add,GND,C9-1)
Netlist(Add,GND,U5-1)
Netlist(Add,GND,CONN3-3)
Netlist(Add,GND,CONN3-4)
Netlist(Add,GND,R24-2)
Netlist(Add,GND,R41-2)
Netlist(Add,GND,R21-2)
Netlist(Add,GND,R15-1)
Netlist(Add,GND,R5-2)
Netlist(Add,GND,R10-1)
Netlist(Add,GND,R2-1)
Netlist(Add,GND,R37-1)
Netlist(Add,GND,R38-1)
Netlist(Add,GND,U3-10)
Netlist(Add,GND,C111-1)
Netlist(Add,GND,C110-2)
Netlist(Add,GND,C109-1)
Netlist(Add,GND,C108-2)
Netlist(Add,GND,C107-1)
Netlist(Add,GND,C106-2)
Netlist(Add,GND,C105-1)
Netlist(Add,GND,C104-2)
Netlist(Add,GND,TP18-1)
Netlist(Add,GND,TP14-1)
Netlist(Add,GND,TP13-1)
Netlist(Add,GND,TP12-1)
Netlist(Add,GND,C1001-1)
Netlist(Add,GND,C1000-2)
Netlist(Add,GND,CONN5-2)
Netlist(Add,GND,CONN4-2)
Netlist(Sort)
Netlist(Thaw)
ElementList(Start)
ElementList(Need,"LCD1","DP-650-vertical.fp","DP-650")
ElementSetAttr("LCD1","device","DIGITAL_VOLT_METER")
ElementSetAttr("LCD1","manufacturer","unknown")
ElementSetAttr("LCD1","manufacturer_part_number","unknown")
ElementSetAttr("LCD1","vendor","unknown")
ElementSetAttr("LCD1","vendor_part_number","unknown")
ElementList(Need,"Q100","TO92","unknown")
ElementSetAttr("Q100","device","2N3906")
ElementSetAttr("Q100","manufacturer","unknown")
ElementSetAttr("Q100","manufacturer_part_number","unknown")
ElementSetAttr("Q100","vendor","unknown")
ElementSetAttr("Q100","vendor_part_number","unknown")
ChangePinName("Q100", 2, "B")
ChangePinName("Q100", 3, "E")
ChangePinName("Q100", 1, "C")
ElementList(Need,"C103","rcy(100,bar)","0.1uF")
ElementSetAttr("C103","device","CAPACITOR")
ElementSetAttr("C103","manufacturer","unknown")
ElementSetAttr("C103","manufacturer_part_number","unknown")
ElementSetAttr("C103","vendor","unknown")
ElementSetAttr("C103","vendor_part_number","unknown")
ChangePinName("C103", 2, "2")
ChangePinName("C103", 1, "1")
ElementList(Need,"C102","rcy(100,bar)","0.1uF")
ElementSetAttr("C102","device","CAPACITOR")
ElementSetAttr("C102","manufacturer","unknown")
ElementSetAttr("C102","manufacturer_part_number","unknown")
ElementSetAttr("C102","vendor","unknown")
ElementSetAttr("C102","vendor_part_number","unknown")
ChangePinName("C102", 2, "2")
ChangePinName("C102", 1, "1")
ElementList(Need,"C101","rcy(100)","0.1uF")
ElementSetAttr("C101","device","CAPACITOR")
ElementSetAttr("C101","manufacturer","unknown")
ElementSetAttr("C101","manufacturer_part_number","unknown")
ElementSetAttr("C101","vendor","unknown")
ElementSetAttr("C101","vendor_part_number","unknown")
ChangePinName("C101", 2, "2")
ChangePinName("C101", 1, "1")
ElementList(Need,"R100","acy(400)","15K")
ElementSetAttr("R100","device","RESISTOR")
ElementSetAttr("R100","manufacturer","unknown")
ElementSetAttr("R100","manufacturer_part_number","unknown")
ElementSetAttr("R100","vendor","unknown")
ElementSetAttr("R100","vendor_part_number","unknown")
ChangePinName("R100", 1, "1")
ChangePinName("R100", 2, "2")
ElementList(Need,"R101","acy(400)","525")
ElementSetAttr("R101","device","RESISTOR")
ElementSetAttr("R101","manufacturer","unknown")
ElementSetAttr("R101","manufacturer_part_number","unknown")
ElementSetAttr("R101","vendor","unknown")
ElementSetAttr("R101","vendor_part_number","unknown")
ChangePinName("R101", 1, "1")
ChangePinName("R101", 2, "2")
ElementList(Need,"CONN7","AMPHENOL_BNC_31-5431-ver2","31-5431")
ElementSetAttr("CONN7","device","BNC Connector")
ElementSetAttr("CONN7","manufacturer","unknown")
ElementSetAttr("CONN7","manufacturer_part_number","unknown")
ElementSetAttr("CONN7","vendor","unknown")
ElementSetAttr("CONN7","vendor_part_number","unknown")
ChangePinName("CONN7", 1, "1")
ChangePinName("CONN7", 2, "2")
ElementList(Need,"TP17","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP17","device","TESTPOINT")
ElementSetAttr("TP17","manufacturer","unknown")
ElementSetAttr("TP17","manufacturer_part_number","unknown")
ElementSetAttr("TP17","vendor","unknown")
ElementSetAttr("TP17","vendor_part_number","unknown")
ChangePinName("TP17", 1, "1")
ElementList(Need,"VREG1","TO92","LM78L05")
ElementSetAttr("VREG1","device","7805")
ElementSetAttr("VREG1","manufacturer","unknown")
ElementSetAttr("VREG1","manufacturer_part_number","unknown")
ElementSetAttr("VREG1","vendor","unknown")
ElementSetAttr("VREG1","vendor_part_number","unknown")
ChangePinName("VREG1", 1, "1")
ChangePinName("VREG1", 2, "2")
ChangePinName("VREG1", 3, "3")
ElementList(Need,"C19","ACY300","0.01uF")
ElementSetAttr("C19","device","CAPACITOR")
ElementSetAttr("C19","manufacturer","unknown")
ElementSetAttr("C19","manufacturer_part_number","unknown")
ElementSetAttr("C19","vendor","unknown")
ElementSetAttr("C19","vendor_part_number","unknown")
ChangePinName("C19", 2, "2")
ChangePinName("C19", 1, "1")
ElementList(Need,"C18","RCY100","0.1uF")
ElementSetAttr("C18","device","CAPACITOR")
ElementSetAttr("C18","manufacturer","unknown")
ElementSetAttr("C18","manufacturer_part_number","unknown")
ElementSetAttr("C18","vendor","unknown")
ElementSetAttr("C18","vendor_part_number","unknown")
ChangePinName("C18", 2, "2")
ChangePinName("C18", 1, "1")
ElementList(Need,"LED2","LPF-C013301S","See BOM Note #1")
ElementSetAttr("LED2","device","LED")
ElementSetAttr("LED2","manufacturer","unknown")
ElementSetAttr("LED2","manufacturer_part_number","unknown")
ElementSetAttr("LED2","vendor","unknown")
ElementSetAttr("LED2","vendor_part_number","unknown")
ChangePinName("LED2", 5, "A")
ChangePinName("LED2", 6, "K")
ChangePinName("LED2", 1, "A")
ChangePinName("LED2", 2, "K")
ChangePinName("LED2", 3, "A")
ChangePinName("LED2", 4, "K")
ElementList(Need,"S3","CK_7201SYAQE.fp","7201SYAQE")
ElementSetAttr("S3","device","Dual_Two_Way_Switch")
ElementSetAttr("S3","manufacturer","unknown")
ElementSetAttr("S3","manufacturer_part_number","unknown")
ElementSetAttr("S3","vendor","unknown")
ElementSetAttr("S3","vendor_part_number","unknown")
ChangePinName("S3", 8, "8")
ChangePinName("S3", 7, "7")
ChangePinName("S3", 3, "3")
ChangePinName("S3", 2, "2")
ChangePinName("S3", 1, "1")
ChangePinName("S3", 6, "6")
ChangePinName("S3", 5, "5")
ChangePinName("S3", 4, "4")
ElementList(Need,"S1","CK_7201SYAQE.fp","7201SYAQE")
ElementSetAttr("S1","device","Dual_Two_Way_Switch")
ElementSetAttr("S1","manufacturer","unknown")
ElementSetAttr("S1","manufacturer_part_number","unknown")
ElementSetAttr("S1","vendor","unknown")
ElementSetAttr("S1","vendor_part_number","unknown")
ChangePinName("S1", 8, "8")
ChangePinName("S1", 7, "7")
ChangePinName("S1", 3, "3")
ChangePinName("S1", 2, "2")
ChangePinName("S1", 1, "1")
ChangePinName("S1", 6, "6")
ChangePinName("S1", 5, "5")
ChangePinName("S1", 4, "4")
ElementList(Need,"S2","molex-22-23-2041-mini_4_vert.fp","50D36-01-1-AJN")
ElementSetAttr("S2","device","SP4T")
ElementSetAttr("S2","manufacturer","unknown")
ElementSetAttr("S2","manufacturer_part_number","unknown")
ElementSetAttr("S2","vendor","unknown")
ElementSetAttr("S2","vendor_part_number","unknown")
ChangePinName("S2", 4, "4")
ChangePinName("S2", 1, "1")
ChangePinName("S2", 3, "3")
ChangePinName("S2", 2, "2")
ElementList(Need,"Q1","TO92","2N3904")
ElementSetAttr("Q1","device","2N3904")
ElementSetAttr("Q1","manufacturer","unknown")
ElementSetAttr("Q1","manufacturer_part_number","unknown")
ElementSetAttr("Q1","vendor","unknown")
ElementSetAttr("Q1","vendor_part_number","unknown")
ChangePinName("Q1", 2, "2")
ChangePinName("Q1", 1, "1")
ChangePinName("Q1", 3, "3")
ElementList(Need,"Q2","TO92","2N3904")
ElementSetAttr("Q2","device","2N3904")
ElementSetAttr("Q2","manufacturer","unknown")
ElementSetAttr("Q2","manufacturer_part_number","unknown")
ElementSetAttr("Q2","vendor","unknown")
ElementSetAttr("Q2","vendor_part_number","unknown")
ChangePinName("Q2", 2, "2")
ChangePinName("Q2", 1, "1")
ChangePinName("Q2", 3, "3")
ElementList(Need,"TP6","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP6","device","TESTPOINT")
ElementSetAttr("TP6","manufacturer","unknown")
ElementSetAttr("TP6","manufacturer_part_number","unknown")
ElementSetAttr("TP6","vendor","unknown")
ElementSetAttr("TP6","vendor_part_number","unknown")
ChangePinName("TP6", 1, "1")
ElementList(Need,"U2","DIP16","74221")
ElementSetAttr("U2","device","74221")
ElementSetAttr("U2","manufacturer","unknown")
ElementSetAttr("U2","manufacturer_part_number","unknown")
ElementSetAttr("U2","vendor","unknown")
ElementSetAttr("U2","vendor_part_number","unknown")
ChangePinName("U2", 16, "Vcc")
ChangePinName("U2", 8, "GND")
ChangePinName("U2", 4, "\_Q\_")
ChangePinName("U2", 13, "Q")
ChangePinName("U2", 3, "\_CLR\_")
ChangePinName("U2", 14, "CX")
ChangePinName("U2", 2, "B")
ChangePinName("U2", 15, "RX/CX")
ChangePinName("U2", 1, "\_A\_")
ChangePinName("U2", 12, "\_Q\_")
ChangePinName("U2", 5, "Q")
ChangePinName("U2", 11, "\_CLR\_")
ChangePinName("U2", 8, "GND")
ChangePinName("U2", 10, "B")
ChangePinName("U2", 7, "RX/CX")
ChangePinName("U2", 9, "\_A\_")
ElementList(Need,"C17","RCY100P","1.0uF")
ElementSetAttr("C17","device","POLARIZED_CAPACITOR")
ElementSetAttr("C17","manufacturer","unknown")
ElementSetAttr("C17","manufacturer_part_number","unknown")
ElementSetAttr("C17","vendor","unknown")
ElementSetAttr("C17","vendor_part_number","unknown")
ChangePinName("C17", 2, "-")
ChangePinName("C17", 1, "+")
ElementList(Need,"C7","ACY400","1.0uF")
ElementSetAttr("C7","device","CAPACITOR")
ElementSetAttr("C7","manufacturer","unknown")
ElementSetAttr("C7","manufacturer_part_number","unknown")
ElementSetAttr("C7","vendor","unknown")
ElementSetAttr("C7","vendor_part_number","unknown")
ChangePinName("C7", 2, "2")
ChangePinName("C7", 1, "1")
ElementList(Need,"C5","ACY400","1.0uF")
ElementSetAttr("C5","device","CAPACITOR")
ElementSetAttr("C5","manufacturer","unknown")
ElementSetAttr("C5","manufacturer_part_number","unknown")
ElementSetAttr("C5","vendor","unknown")
ElementSetAttr("C5","vendor_part_number","unknown")
ChangePinName("C5", 2, "2")
ChangePinName("C5", 1, "1")
ElementList(Need,"C4","ACY600","2.0uF")
ElementSetAttr("C4","device","CAPACITOR")
ElementSetAttr("C4","manufacturer","unknown")
ElementSetAttr("C4","manufacturer_part_number","unknown")
ElementSetAttr("C4","vendor","unknown")
ElementSetAttr("C4","vendor_part_number","unknown")
ChangePinName("C4", 2, "2")
ChangePinName("C4", 1, "1")
ElementList(Need,"U4","DIP8","LF356")
ElementSetAttr("U4","device","LF356")
ElementSetAttr("U4","manufacturer","unknown")
ElementSetAttr("U4","manufacturer_part_number","unknown")
ElementSetAttr("U4","vendor","unknown")
ElementSetAttr("U4","vendor_part_number","unknown")
ChangePinName("U4", 3, "IN+")
ChangePinName("U4", 5, "NULL")
ChangePinName("U4", 7, "+V")
ChangePinName("U4", 1, "NULL")
ChangePinName("U4", 8, "N.C.")
ChangePinName("U4", 6, "OUT")
ChangePinName("U4", 4, "V-")
ChangePinName("U4", 2, "IN-")
ElementList(Need,"U1","DIP8","LM331")
ElementSetAttr("U1","device","LM331")
ElementSetAttr("U1","manufacturer","unknown")
ElementSetAttr("U1","manufacturer_part_number","unknown")
ElementSetAttr("U1","vendor","unknown")
ElementSetAttr("U1","vendor_part_number","unknown")
ChangePinName("U1", 3, "Freq. Out")
ChangePinName("U1", 5, "R/C")
ChangePinName("U1", 7, "Comp. In")
ChangePinName("U1", 1, "Current Out")
ChangePinName("U1", 8, "Vs")
ChangePinName("U1", 6, "Threshold")
ChangePinName("U1", 4, "GND")
ChangePinName("U1", 2, "Ref. Current")
ElementList(Need,"R42","ACY400","52.3")
ElementSetAttr("R42","device","RESISTOR")
ElementSetAttr("R42","manufacturer","unknown")
ElementSetAttr("R42","manufacturer_part_number","unknown")
ElementSetAttr("R42","vendor","unknown")
ElementSetAttr("R42","vendor_part_number","unknown")
ChangePinName("R42", 1, "1")
ChangePinName("R42", 2, "2")
ElementList(Need,"U6","DIP8","INA129")
ElementSetAttr("U6","device","INA129")
ElementSetAttr("U6","manufacturer","unknown")
ElementSetAttr("U6","manufacturer_part_number","unknown")
ElementSetAttr("U6","vendor","unknown")
ElementSetAttr("U6","vendor_part_number","unknown")
ChangePinName("U6", 3, "+Vin")
ChangePinName("U6", 5, "Inull1")
ChangePinName("U6", 4, "Inull")
ChangePinName("U6", 7, "-Vs")
ChangePinName("U6", 6, "Out")
ChangePinName("U6", 8, "RG2")
ChangePinName("U6", 2, "-Vin")
ChangePinName("U6", 1, "RG1")
ElementList(Need,"TP10","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP10","device","TESTPOINT")
ElementSetAttr("TP10","manufacturer","unknown")
ElementSetAttr("TP10","manufacturer_part_number","unknown")
ElementSetAttr("TP10","vendor","unknown")
ElementSetAttr("TP10","vendor_part_number","unknown")
ChangePinName("TP10", 1, "1")
ElementList(Need,"TP9","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP9","device","TESTPOINT")
ElementSetAttr("TP9","manufacturer","unknown")
ElementSetAttr("TP9","manufacturer_part_number","unknown")
ElementSetAttr("TP9","vendor","unknown")
ElementSetAttr("TP9","vendor_part_number","unknown")
ChangePinName("TP9", 1, "1")
ElementList(Need,"TP8","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP8","device","TESTPOINT")
ElementSetAttr("TP8","manufacturer","unknown")
ElementSetAttr("TP8","manufacturer_part_number","unknown")
ElementSetAttr("TP8","vendor","unknown")
ElementSetAttr("TP8","vendor_part_number","unknown")
ChangePinName("TP8", 1, "1")
ElementList(Need,"TP7","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP7","device","TESTPOINT")
ElementSetAttr("TP7","manufacturer","unknown")
ElementSetAttr("TP7","manufacturer_part_number","unknown")
ElementSetAttr("TP7","vendor","unknown")
ElementSetAttr("TP7","vendor_part_number","unknown")
ChangePinName("TP7", 1, "1")
ElementList(Need,"TP5","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP5","device","TESTPOINT")
ElementSetAttr("TP5","manufacturer","unknown")
ElementSetAttr("TP5","manufacturer_part_number","unknown")
ElementSetAttr("TP5","vendor","unknown")
ElementSetAttr("TP5","vendor_part_number","unknown")
ChangePinName("TP5", 1, "1")
ElementList(Need,"TP4","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP4","device","TESTPOINT")
ElementSetAttr("TP4","manufacturer","unknown")
ElementSetAttr("TP4","manufacturer_part_number","unknown")
ElementSetAttr("TP4","vendor","unknown")
ElementSetAttr("TP4","vendor_part_number","unknown")
ChangePinName("TP4", 1, "1")
ElementList(Need,"TP3","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP3","device","TESTPOINT")
ElementSetAttr("TP3","manufacturer","unknown")
ElementSetAttr("TP3","manufacturer_part_number","unknown")
ElementSetAttr("TP3","vendor","unknown")
ElementSetAttr("TP3","vendor_part_number","unknown")
ChangePinName("TP3", 1, "1")
ElementList(Need,"TP2","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP2","device","TESTPOINT")
ElementSetAttr("TP2","manufacturer","unknown")
ElementSetAttr("TP2","manufacturer_part_number","unknown")
ElementSetAttr("TP2","vendor","unknown")
ElementSetAttr("TP2","vendor_part_number","unknown")
ChangePinName("TP2", 1, "1")
ElementList(Need,"TP1","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP1","device","TESTPOINT")
ElementSetAttr("TP1","manufacturer","unknown")
ElementSetAttr("TP1","manufacturer_part_number","unknown")
ElementSetAttr("TP1","vendor","unknown")
ElementSetAttr("TP1","vendor_part_number","unknown")
ChangePinName("TP1", 1, "1")
ElementList(Need,"R40","ACY400","1.5K")
ElementSetAttr("R40","device","RESISTOR")
ElementSetAttr("R40","manufacturer","unknown")
ElementSetAttr("R40","manufacturer_part_number","unknown")
ElementSetAttr("R40","vendor","unknown")
ElementSetAttr("R40","vendor_part_number","unknown")
ChangePinName("R40", 1, "1")
ChangePinName("R40", 2, "2")
ElementList(Need,"D2","ALF400","1N4148")
ElementSetAttr("D2","device","DIODE")
ElementSetAttr("D2","manufacturer","unknown")
ElementSetAttr("D2","manufacturer_part_number","unknown")
ElementSetAttr("D2","vendor","unknown")
ElementSetAttr("D2","vendor_part_number","unknown")
ChangePinName("D2", 1, "1")
ChangePinName("D2", 2, "2")
ElementList(Need,"LED1","T1.75_LED","Generic Yellow LED")
ElementSetAttr("LED1","device","LED")
ElementSetAttr("LED1","manufacturer","unknown")
ElementSetAttr("LED1","manufacturer_part_number","unknown")
ElementSetAttr("LED1","vendor","unknown")
ElementSetAttr("LED1","vendor_part_number","unknown")
ChangePinName("LED1", 2, "K")
ChangePinName("LED1", 1, "A")
ElementList(Need,"C14","ACY300","0.1uF")
ElementSetAttr("C14","device","CAPACITOR")
ElementSetAttr("C14","manufacturer","unknown")
ElementSetAttr("C14","manufacturer_part_number","unknown")
ElementSetAttr("C14","vendor","unknown")
ElementSetAttr("C14","vendor_part_number","unknown")
ChangePinName("C14", 2, "2")
ChangePinName("C14", 1, "1")
ElementList(Need,"C15","ACY300","0.1uF")
ElementSetAttr("C15","device","CAPACITOR")
ElementSetAttr("C15","manufacturer","unknown")
ElementSetAttr("C15","manufacturer_part_number","unknown")
ElementSetAttr("C15","vendor","unknown")
ElementSetAttr("C15","vendor_part_number","unknown")
ChangePinName("C15", 2, "2")
ChangePinName("C15", 1, "1")
ElementList(Need,"CONN2","AMPHENOL_BNC_31-5431-ver2","31-5431")
ElementSetAttr("CONN2","device","BNC Connector")
ElementSetAttr("CONN2","manufacturer","unknown")
ElementSetAttr("CONN2","manufacturer_part_number","unknown")
ElementSetAttr("CONN2","vendor","unknown")
ElementSetAttr("CONN2","vendor_part_number","unknown")
ChangePinName("CONN2", 4, "4")
ChangePinName("CONN2", 3, "3")
ChangePinName("CONN2", 1, "1")
ChangePinName("CONN2", 2, "2")
ElementList(Need,"CONN1","AMPHENOL_BNC_31-5431-ver2","31-5431")
ElementSetAttr("CONN1","device","BNC Connector")
ElementSetAttr("CONN1","manufacturer","unknown")
ElementSetAttr("CONN1","manufacturer_part_number","unknown")
ElementSetAttr("CONN1","vendor","unknown")
ElementSetAttr("CONN1","vendor_part_number","unknown")
ChangePinName("CONN1", 4, "4")
ChangePinName("CONN1", 3, "3")
ChangePinName("CONN1", 1, "1")
ChangePinName("CONN1", 2, "2")
ElementList(Need,"BUZ2","PB-1408.fp","PB-1408")
ElementSetAttr("BUZ2","device","BEEPER")
ElementSetAttr("BUZ2","manufacturer","unknown")
ElementSetAttr("BUZ2","manufacturer_part_number","unknown")
ElementSetAttr("BUZ2","vendor","unknown")
ElementSetAttr("BUZ2","vendor_part_number","unknown")
ChangePinName("BUZ2", 2, "2")
ChangePinName("BUZ2", 1, "1")
ElementList(Need,"C16","ACY300","0.1uF")
ElementSetAttr("C16","device","CAPACITOR")
ElementSetAttr("C16","manufacturer","unknown")
ElementSetAttr("C16","manufacturer_part_number","unknown")
ElementSetAttr("C16","vendor","unknown")
ElementSetAttr("C16","vendor_part_number","unknown")
ChangePinName("C16", 2, "2")
ChangePinName("C16", 1, "1")
ElementList(Need,"C1","acy(886)","4.7uF")
ElementSetAttr("C1","device","CAPACITOR")
ElementSetAttr("C1","manufacturer","unknown")
ElementSetAttr("C1","manufacturer_part_number","unknown")
ElementSetAttr("C1","vendor","unknown")
ElementSetAttr("C1","vendor_part_number","unknown")
ChangePinName("C1", 2, "2")
ChangePinName("C1", 1, "1")
ElementList(Need,"R28","ACY400","470K")
ElementSetAttr("R28","device","RESISTOR")
ElementSetAttr("R28","manufacturer","unknown")
ElementSetAttr("R28","manufacturer_part_number","unknown")
ElementSetAttr("R28","vendor","unknown")
ElementSetAttr("R28","vendor_part_number","unknown")
ChangePinName("R28", 1, "1")
ChangePinName("R28", 2, "2")
ElementList(Need,"R27","ACY400","4.7K")
ElementSetAttr("R27","device","RESISTOR")
ElementSetAttr("R27","manufacturer","unknown")
ElementSetAttr("R27","manufacturer_part_number","unknown")
ElementSetAttr("R27","vendor","unknown")
ElementSetAttr("R27","vendor_part_number","unknown")
ChangePinName("R27", 1, "1")
ChangePinName("R27", 2, "2")
ElementList(Need,"C8","RCY100","0.1uF")
ElementSetAttr("C8","device","CAPACITOR")
ElementSetAttr("C8","manufacturer","unknown")
ElementSetAttr("C8","manufacturer_part_number","unknown")
ElementSetAttr("C8","vendor","unknown")
ElementSetAttr("C8","vendor_part_number","unknown")
ChangePinName("C8", 2, "2")
ChangePinName("C8", 1, "1")
ElementList(Need,"C10","RCY100","0.1uF")
ElementSetAttr("C10","device","CAPACITOR")
ElementSetAttr("C10","manufacturer","unknown")
ElementSetAttr("C10","manufacturer_part_number","unknown")
ElementSetAttr("C10","vendor","unknown")
ElementSetAttr("C10","vendor_part_number","unknown")
ChangePinName("C10", 2, "2")
ChangePinName("C10", 1, "1")
ElementList(Need,"C9","RCY100","0.1uF")
ElementSetAttr("C9","device","CAPACITOR")
ElementSetAttr("C9","manufacturer","unknown")
ElementSetAttr("C9","manufacturer_part_number","unknown")
ElementSetAttr("C9","vendor","unknown")
ElementSetAttr("C9","vendor_part_number","unknown")
ChangePinName("C9", 2, "2")
ChangePinName("C9", 1, "1")
ElementList(Need,"U5","DIP8","LM555")
ElementSetAttr("U5","device","LM555")
ElementSetAttr("U5","manufacturer","unknown")
ElementSetAttr("U5","manufacturer_part_number","unknown")
ElementSetAttr("U5","vendor","unknown")
ElementSetAttr("U5","vendor_part_number","unknown")
ChangePinName("U5", 1, "1")
ChangePinName("U5", 2, "2")
ChangePinName("U5", 4, "4")
ChangePinName("U5", 8, "8")
ChangePinName("U5", 7, "7")
ChangePinName("U5", 6, "6")
ChangePinName("U5", 5, "5")
ChangePinName("U5", 3, "3")
ElementList(Need,"R26","ACY400","2.2K")
ElementSetAttr("R26","device","RESISTOR")
ElementSetAttr("R26","manufacturer","unknown")
ElementSetAttr("R26","manufacturer_part_number","unknown")
ElementSetAttr("R26","vendor","unknown")
ElementSetAttr("R26","vendor_part_number","unknown")
ChangePinName("R26", 1, "1")
ChangePinName("R26", 2, "2")
ElementList(Need,"R25","ACY400","100K")
ElementSetAttr("R25","device","RESISTOR")
ElementSetAttr("R25","manufacturer","unknown")
ElementSetAttr("R25","manufacturer_part_number","unknown")
ElementSetAttr("R25","vendor","unknown")
ElementSetAttr("R25","vendor_part_number","unknown")
ChangePinName("R25", 1, "1")
ChangePinName("R25", 2, "2")
ElementList(Need,"CONN3","molex-22-23-2041-mini_4_vert.fp","DP-650")
ElementSetAttr("CONN3","device","DIGITAL_VOLT_METER")
ElementSetAttr("CONN3","manufacturer","unknown")
ElementSetAttr("CONN3","manufacturer_part_number","unknown")
ElementSetAttr("CONN3","vendor","unknown")
ElementSetAttr("CONN3","vendor_part_number","unknown")
ChangePinName("CONN3", 1, "1")
ChangePinName("CONN3", 4, "4")
ChangePinName("CONN3", 2, "2")
ChangePinName("CONN3", 3, "3")
ElementList(Need,"R24","ACY400","1K")
ElementSetAttr("R24","device","RESISTOR")
ElementSetAttr("R24","manufacturer","unknown")
ElementSetAttr("R24","manufacturer_part_number","unknown")
ElementSetAttr("R24","vendor","unknown")
ElementSetAttr("R24","vendor_part_number","unknown")
ChangePinName("R24", 1, "1")
ChangePinName("R24", 2, "2")
ElementList(Need,"R23","ACY400","150K")
ElementSetAttr("R23","device","RESISTOR")
ElementSetAttr("R23","manufacturer","unknown")
ElementSetAttr("R23","manufacturer_part_number","unknown")
ElementSetAttr("R23","vendor","unknown")
ElementSetAttr("R23","vendor_part_number","unknown")
ChangePinName("R23", 1, "1")
ChangePinName("R23", 2, "2")
ElementList(Need,"R41","molex-22-23-2031-mini_3_vert.fp","5K")
ElementSetAttr("R41","device","VARIABLE_RESISTOR")
ElementSetAttr("R41","manufacturer","unknown")
ElementSetAttr("R41","manufacturer_part_number","unknown")
ElementSetAttr("R41","vendor","unknown")
ElementSetAttr("R41","vendor_part_number","unknown")
ChangePinName("R41", 1, "1")
ChangePinName("R41", 2, "2")
ChangePinName("R41", 3, "3")
ElementList(Need,"R21","molex-22-23-2031-mini_3_vert.fp","5K")
ElementSetAttr("R21","device","VARIABLE_RESISTOR")
ElementSetAttr("R21","manufacturer","unknown")
ElementSetAttr("R21","manufacturer_part_number","unknown")
ElementSetAttr("R21","vendor","unknown")
ElementSetAttr("R21","vendor_part_number","unknown")
ChangePinName("R21", 1, "1")
ChangePinName("R21", 2, "2")
ChangePinName("R21", 3, "3")
ElementList(Need,"R22","ACY400","2.2K")
ElementSetAttr("R22","device","RESISTOR")
ElementSetAttr("R22","manufacturer","unknown")
ElementSetAttr("R22","manufacturer_part_number","unknown")
ElementSetAttr("R22","vendor","unknown")
ElementSetAttr("R22","vendor_part_number","unknown")
ChangePinName("R22", 1, "1")
ChangePinName("R22", 2, "2")
ElementList(Need,"R19","ACY400","4.7K")
ElementSetAttr("R19","device","RESISTOR")
ElementSetAttr("R19","manufacturer","unknown")
ElementSetAttr("R19","manufacturer_part_number","unknown")
ElementSetAttr("R19","vendor","unknown")
ElementSetAttr("R19","vendor_part_number","unknown")
ChangePinName("R19", 1, "1")
ChangePinName("R19", 2, "2")
ElementList(Need,"R20","ACY400","1M")
ElementSetAttr("R20","device","RESISTOR")
ElementSetAttr("R20","manufacturer","unknown")
ElementSetAttr("R20","manufacturer_part_number","unknown")
ElementSetAttr("R20","vendor","unknown")
ElementSetAttr("R20","vendor_part_number","unknown")
ChangePinName("R20", 1, "1")
ChangePinName("R20", 2, "2")
ElementList(Need,"R18","ACY400","2.2K")
ElementSetAttr("R18","device","RESISTOR")
ElementSetAttr("R18","manufacturer","unknown")
ElementSetAttr("R18","manufacturer_part_number","unknown")
ElementSetAttr("R18","vendor","unknown")
ElementSetAttr("R18","vendor_part_number","unknown")
ChangePinName("R18", 1, "1")
ChangePinName("R18", 2, "2")
ElementList(Need,"R16","ACY400","4.7K")
ElementSetAttr("R16","device","RESISTOR")
ElementSetAttr("R16","manufacturer","unknown")
ElementSetAttr("R16","manufacturer_part_number","unknown")
ElementSetAttr("R16","vendor","unknown")
ElementSetAttr("R16","vendor_part_number","unknown")
ChangePinName("R16", 1, "1")
ChangePinName("R16", 2, "2")
ElementList(Need,"R17","ACY400","1M")
ElementSetAttr("R17","device","RESISTOR")
ElementSetAttr("R17","manufacturer","unknown")
ElementSetAttr("R17","manufacturer_part_number","unknown")
ElementSetAttr("R17","vendor","unknown")
ElementSetAttr("R17","vendor_part_number","unknown")
ChangePinName("R17", 1, "1")
ChangePinName("R17", 2, "2")
ElementList(Need,"R14","ACY400","500")
ElementSetAttr("R14","device","RESISTOR")
ElementSetAttr("R14","manufacturer","unknown")
ElementSetAttr("R14","manufacturer_part_number","unknown")
ElementSetAttr("R14","vendor","unknown")
ElementSetAttr("R14","vendor_part_number","unknown")
ChangePinName("R14", 1, "1")
ChangePinName("R14", 2, "2")
ElementList(Need,"R15","ACY400","1K")
ElementSetAttr("R15","device","RESISTOR")
ElementSetAttr("R15","manufacturer","unknown")
ElementSetAttr("R15","manufacturer_part_number","unknown")
ElementSetAttr("R15","vendor","unknown")
ElementSetAttr("R15","vendor_part_number","unknown")
ChangePinName("R15", 1, "1")
ChangePinName("R15", 2, "2")
ElementList(Need,"C6","ACY400","1.0uF")
ElementSetAttr("C6","device","CAPACITOR")
ElementSetAttr("C6","manufacturer","unknown")
ElementSetAttr("C6","manufacturer_part_number","unknown")
ElementSetAttr("C6","vendor","unknown")
ElementSetAttr("C6","vendor_part_number","unknown")
ChangePinName("C6", 2, "2")
ChangePinName("C6", 1, "1")
ElementList(Need,"R5","ACY400","18K")
ElementSetAttr("R5","device","RESISTOR")
ElementSetAttr("R5","manufacturer","unknown")
ElementSetAttr("R5","manufacturer_part_number","unknown")
ElementSetAttr("R5","vendor","unknown")
ElementSetAttr("R5","vendor_part_number","unknown")
ChangePinName("R5", 1, "1")
ChangePinName("R5", 2, "2")
ElementList(Need,"R13","ACY400","470K")
ElementSetAttr("R13","device","RESISTOR")
ElementSetAttr("R13","manufacturer","unknown")
ElementSetAttr("R13","manufacturer_part_number","unknown")
ElementSetAttr("R13","vendor","unknown")
ElementSetAttr("R13","vendor_part_number","unknown")
ChangePinName("R13", 1, "1")
ChangePinName("R13", 2, "2")
ElementList(Need,"R12","ACY400","470K")
ElementSetAttr("R12","device","RESISTOR")
ElementSetAttr("R12","manufacturer","unknown")
ElementSetAttr("R12","manufacturer_part_number","unknown")
ElementSetAttr("R12","vendor","unknown")
ElementSetAttr("R12","vendor_part_number","unknown")
ChangePinName("R12", 1, "1")
ChangePinName("R12", 2, "2")
ElementList(Need,"R10","ACY400","100K")
ElementSetAttr("R10","device","RESISTOR")
ElementSetAttr("R10","manufacturer","unknown")
ElementSetAttr("R10","manufacturer_part_number","unknown")
ElementSetAttr("R10","vendor","unknown")
ElementSetAttr("R10","vendor_part_number","unknown")
ChangePinName("R10", 1, "1")
ChangePinName("R10", 2, "2")
ElementList(Need,"R11","ACY400","470K")
ElementSetAttr("R11","device","RESISTOR")
ElementSetAttr("R11","manufacturer","unknown")
ElementSetAttr("R11","manufacturer_part_number","unknown")
ElementSetAttr("R11","vendor","unknown")
ElementSetAttr("R11","vendor_part_number","unknown")
ChangePinName("R11", 1, "1")
ChangePinName("R11", 2, "2")
ElementList(Need,"BUZ1","AI-2429-TWT-12V-3-R.fp","AI-2429-TWT-12V-3-R")
ElementSetAttr("BUZ1","device","BEEPER")
ElementSetAttr("BUZ1","manufacturer","unknown")
ElementSetAttr("BUZ1","manufacturer_part_number","unknown")
ElementSetAttr("BUZ1","vendor","unknown")
ElementSetAttr("BUZ1","vendor_part_number","unknown")
ChangePinName("BUZ1", 2, "2")
ChangePinName("BUZ1", 1, "1")
ElementList(Need,"R9","molex-22-23-2031-mini_3_vert.fp","25K")
ElementSetAttr("R9","device","VARIABLE_RESISTOR")
ElementSetAttr("R9","manufacturer","unknown")
ElementSetAttr("R9","manufacturer_part_number","unknown")
ElementSetAttr("R9","vendor","unknown")
ElementSetAttr("R9","vendor_part_number","unknown")
ChangePinName("R9", 1, "1")
ChangePinName("R9", 2, "2")
ChangePinName("R9", 3, "3")
ElementList(Need,"R8","ACY400","2.2K")
ElementSetAttr("R8","device","RESISTOR")
ElementSetAttr("R8","manufacturer","unknown")
ElementSetAttr("R8","manufacturer_part_number","unknown")
ElementSetAttr("R8","vendor","unknown")
ElementSetAttr("R8","vendor_part_number","unknown")
ChangePinName("R8", 1, "1")
ChangePinName("R8", 2, "2")
ElementList(Need,"R3","ACY400","18K")
ElementSetAttr("R3","device","RESISTOR")
ElementSetAttr("R3","manufacturer","unknown")
ElementSetAttr("R3","manufacturer_part_number","unknown")
ElementSetAttr("R3","vendor","unknown")
ElementSetAttr("R3","vendor_part_number","unknown")
ChangePinName("R3", 1, "1")
ChangePinName("R3", 2, "2")
ElementList(Need,"R2","ACY400","56K")
ElementSetAttr("R2","device","RESISTOR")
ElementSetAttr("R2","manufacturer","unknown")
ElementSetAttr("R2","manufacturer_part_number","unknown")
ElementSetAttr("R2","vendor","unknown")
ElementSetAttr("R2","vendor_part_number","unknown")
ChangePinName("R2", 1, "1")
ChangePinName("R2", 2, "2")
ElementList(Need,"R1","ACY400","22K")
ElementSetAttr("R1","device","RESISTOR")
ElementSetAttr("R1","manufacturer","unknown")
ElementSetAttr("R1","manufacturer_part_number","unknown")
ElementSetAttr("R1","vendor","unknown")
ElementSetAttr("R1","vendor_part_number","unknown")
ChangePinName("R1", 1, "1")
ChangePinName("R1", 2, "2")
ElementList(Need,"R4","ACY400","10K")
ElementSetAttr("R4","device","RESISTOR")
ElementSetAttr("R4","manufacturer","unknown")
ElementSetAttr("R4","manufacturer_part_number","unknown")
ElementSetAttr("R4","vendor","unknown")
ElementSetAttr("R4","vendor_part_number","unknown")
ChangePinName("R4", 1, "1")
ChangePinName("R4", 2, "2")
ElementList(Need,"C2","ACY300","470pF")
ElementSetAttr("C2","device","CAPACITOR")
ElementSetAttr("C2","manufacturer","unknown")
ElementSetAttr("C2","manufacturer_part_number","unknown")
ElementSetAttr("C2","vendor","unknown")
ElementSetAttr("C2","vendor_part_number","unknown")
ChangePinName("C2", 2, "2")
ChangePinName("C2", 1, "1")
ElementList(Need,"R7","ACY400","75K")
ElementSetAttr("R7","device","RESISTOR")
ElementSetAttr("R7","manufacturer","unknown")
ElementSetAttr("R7","manufacturer_part_number","unknown")
ElementSetAttr("R7","vendor","unknown")
ElementSetAttr("R7","vendor_part_number","unknown")
ChangePinName("R7", 1, "1")
ChangePinName("R7", 2, "2")
ElementList(Need,"C3","ACY400","1.0uF")
ElementSetAttr("C3","device","CAPACITOR")
ElementSetAttr("C3","manufacturer","unknown")
ElementSetAttr("C3","manufacturer_part_number","unknown")
ElementSetAttr("C3","vendor","unknown")
ElementSetAttr("C3","vendor_part_number","unknown")
ChangePinName("C3", 2, "2")
ChangePinName("C3", 1, "1")
ElementList(Need,"R6","ACY400","1K")
ElementSetAttr("R6","device","RESISTOR")
ElementSetAttr("R6","manufacturer","unknown")
ElementSetAttr("R6","manufacturer_part_number","unknown")
ElementSetAttr("R6","vendor","unknown")
ElementSetAttr("R6","vendor_part_number","unknown")
ChangePinName("R6", 1, "1")
ChangePinName("R6", 2, "2")
ElementList(Need,"R30","ACY400","4.7K")
ElementSetAttr("R30","device","RESISTOR")
ElementSetAttr("R30","manufacturer","unknown")
ElementSetAttr("R30","manufacturer_part_number","unknown")
ElementSetAttr("R30","vendor","unknown")
ElementSetAttr("R30","vendor_part_number","unknown")
ChangePinName("R30", 1, "1")
ChangePinName("R30", 2, "2")
ElementList(Need,"R29","ACY400","4.7K")
ElementSetAttr("R29","device","RESISTOR")
ElementSetAttr("R29","manufacturer","unknown")
ElementSetAttr("R29","manufacturer_part_number","unknown")
ElementSetAttr("R29","vendor","unknown")
ElementSetAttr("R29","vendor_part_number","unknown")
ChangePinName("R29", 1, "1")
ChangePinName("R29", 2, "2")
ElementList(Need,"D1","ALF400","1N4148")
ElementSetAttr("D1","device","DIODE")
ElementSetAttr("D1","manufacturer","unknown")
ElementSetAttr("D1","manufacturer_part_number","unknown")
ElementSetAttr("D1","vendor","unknown")
ElementSetAttr("D1","vendor_part_number","unknown")
ChangePinName("D1", 1, "1")
ChangePinName("D1", 2, "2")
ElementList(Need,"R33","ACY400","100K")
ElementSetAttr("R33","device","RESISTOR")
ElementSetAttr("R33","manufacturer","unknown")
ElementSetAttr("R33","manufacturer_part_number","unknown")
ElementSetAttr("R33","vendor","unknown")
ElementSetAttr("R33","vendor_part_number","unknown")
ChangePinName("R33", 1, "1")
ChangePinName("R33", 2, "2")
ElementList(Need,"R32","ACY400","2.2K")
ElementSetAttr("R32","device","RESISTOR")
ElementSetAttr("R32","manufacturer","unknown")
ElementSetAttr("R32","manufacturer_part_number","unknown")
ElementSetAttr("R32","vendor","unknown")
ElementSetAttr("R32","vendor_part_number","unknown")
ChangePinName("R32", 1, "1")
ChangePinName("R32", 2, "2")
ElementList(Need,"R31","ACY400","56K")
ElementSetAttr("R31","device","RESISTOR")
ElementSetAttr("R31","manufacturer","unknown")
ElementSetAttr("R31","manufacturer_part_number","unknown")
ElementSetAttr("R31","vendor","unknown")
ElementSetAttr("R31","vendor_part_number","unknown")
ChangePinName("R31", 1, "1")
ChangePinName("R31", 2, "2")
ElementList(Need,"C11","ACY600","2.0uF")
ElementSetAttr("C11","device","CAPACITOR")
ElementSetAttr("C11","manufacturer","unknown")
ElementSetAttr("C11","manufacturer_part_number","unknown")
ElementSetAttr("C11","vendor","unknown")
ElementSetAttr("C11","vendor_part_number","unknown")
ChangePinName("C11", 2, "2")
ChangePinName("C11", 1, "1")
ElementList(Need,"R37","ACY400","100K")
ElementSetAttr("R37","device","RESISTOR")
ElementSetAttr("R37","manufacturer","unknown")
ElementSetAttr("R37","manufacturer_part_number","unknown")
ElementSetAttr("R37","vendor","unknown")
ElementSetAttr("R37","vendor_part_number","unknown")
ChangePinName("R37", 1, "1")
ChangePinName("R37", 2, "2")
ElementList(Need,"R38","ACY400","100K")
ElementSetAttr("R38","device","RESISTOR")
ElementSetAttr("R38","manufacturer","unknown")
ElementSetAttr("R38","manufacturer_part_number","unknown")
ElementSetAttr("R38","vendor","unknown")
ElementSetAttr("R38","vendor_part_number","unknown")
ChangePinName("R38", 1, "1")
ChangePinName("R38", 2, "2")
ElementList(Need,"R39","molex-22-23-2031-mini_3_vert.fp","25K")
ElementSetAttr("R39","device","VARIABLE_RESISTOR")
ElementSetAttr("R39","manufacturer","unknown")
ElementSetAttr("R39","manufacturer_part_number","unknown")
ElementSetAttr("R39","vendor","unknown")
ElementSetAttr("R39","vendor_part_number","unknown")
ChangePinName("R39", 1, "1")
ChangePinName("R39", 2, "2")
ChangePinName("R39", 3, "3")
ElementList(Need,"R36","ACY400","30K")
ElementSetAttr("R36","device","RESISTOR")
ElementSetAttr("R36","manufacturer","unknown")
ElementSetAttr("R36","manufacturer_part_number","unknown")
ElementSetAttr("R36","vendor","unknown")
ElementSetAttr("R36","vendor_part_number","unknown")
ChangePinName("R36", 1, "1")
ChangePinName("R36", 2, "2")
ElementList(Need,"C13","ACY300","0.01uF")
ElementSetAttr("C13","device","CAPACITOR")
ElementSetAttr("C13","manufacturer","unknown")
ElementSetAttr("C13","manufacturer_part_number","unknown")
ElementSetAttr("C13","vendor","unknown")
ElementSetAttr("C13","vendor_part_number","unknown")
ChangePinName("C13", 2, "2")
ChangePinName("C13", 1, "1")
ElementList(Need,"R35","ACY400","30K")
ElementSetAttr("R35","device","RESISTOR")
ElementSetAttr("R35","manufacturer","unknown")
ElementSetAttr("R35","manufacturer_part_number","unknown")
ElementSetAttr("R35","vendor","unknown")
ElementSetAttr("R35","vendor_part_number","unknown")
ChangePinName("R35", 1, "1")
ChangePinName("R35", 2, "2")
ElementList(Need,"C12","ACY300","0.01uF")
ElementSetAttr("C12","device","CAPACITOR")
ElementSetAttr("C12","manufacturer","unknown")
ElementSetAttr("C12","manufacturer_part_number","unknown")
ElementSetAttr("C12","vendor","unknown")
ElementSetAttr("C12","vendor_part_number","unknown")
ChangePinName("C12", 2, "2")
ChangePinName("C12", 1, "1")
ElementList(Need,"R34","ACY400","1.8K")
ElementSetAttr("R34","device","RESISTOR")
ElementSetAttr("R34","manufacturer","unknown")
ElementSetAttr("R34","manufacturer_part_number","unknown")
ElementSetAttr("R34","vendor","unknown")
ElementSetAttr("R34","vendor_part_number","unknown")
ChangePinName("R34", 1, "1")
ChangePinName("R34", 2, "2")
ElementList(Need,"U3","DIP14","LM339")
ElementSetAttr("U3","device","LM339")
ElementSetAttr("U3","manufacturer","unknown")
ElementSetAttr("U3","manufacturer_part_number","unknown")
ElementSetAttr("U3","vendor","unknown")
ElementSetAttr("U3","vendor_part_number","unknown")
ChangePinName("U3", 12, "12")
ChangePinName("U3", 3, "3")
ChangePinName("U3", 14, "14")
ChangePinName("U3", 8, "8")
ChangePinName("U3", 9, "9")
ChangePinName("U3", 12, "12")
ChangePinName("U3", 3, "3")
ChangePinName("U3", 1, "1")
ChangePinName("U3", 6, "6")
ChangePinName("U3", 7, "7")
ChangePinName("U3", 12, "12")
ChangePinName("U3", 3, "3")
ChangePinName("U3", 2, "2")
ChangePinName("U3", 4, "4")
ChangePinName("U3", 5, "5")
ChangePinName("U3", 12, "12")
ChangePinName("U3", 3, "3")
ChangePinName("U3", 13, "13")
ChangePinName("U3", 10, "10")
ChangePinName("U3", 11, "11")
ElementList(Need,"C111","rcy(100)","0.1uF")
ElementSetAttr("C111","device","CAPACITOR")
ElementSetAttr("C111","manufacturer","unknown")
ElementSetAttr("C111","manufacturer_part_number","unknown")
ElementSetAttr("C111","vendor","unknown")
ElementSetAttr("C111","vendor_part_number","unknown")
ChangePinName("C111", 2, "2")
ChangePinName("C111", 1, "1")
ElementList(Need,"C110","rcy(100)","0.1uF")
ElementSetAttr("C110","device","CAPACITOR")
ElementSetAttr("C110","manufacturer","unknown")
ElementSetAttr("C110","manufacturer_part_number","unknown")
ElementSetAttr("C110","vendor","unknown")
ElementSetAttr("C110","vendor_part_number","unknown")
ChangePinName("C110", 2, "2")
ChangePinName("C110", 1, "1")
ElementList(Need,"C109","rcy(100,bar)","0.1uF")
ElementSetAttr("C109","device","CAPACITOR")
ElementSetAttr("C109","manufacturer","unknown")
ElementSetAttr("C109","manufacturer_part_number","unknown")
ElementSetAttr("C109","vendor","unknown")
ElementSetAttr("C109","vendor_part_number","unknown")
ChangePinName("C109", 2, "2")
ChangePinName("C109", 1, "1")
ElementList(Need,"C108","rcy(100,bar)","0.1uF")
ElementSetAttr("C108","device","CAPACITOR")
ElementSetAttr("C108","manufacturer","unknown")
ElementSetAttr("C108","manufacturer_part_number","unknown")
ElementSetAttr("C108","vendor","unknown")
ElementSetAttr("C108","vendor_part_number","unknown")
ChangePinName("C108", 2, "2")
ChangePinName("C108", 1, "1")
ElementList(Need,"C107","rcy(100,bar)","0.1uF")
ElementSetAttr("C107","device","CAPACITOR")
ElementSetAttr("C107","manufacturer","unknown")
ElementSetAttr("C107","manufacturer_part_number","unknown")
ElementSetAttr("C107","vendor","unknown")
ElementSetAttr("C107","vendor_part_number","unknown")
ChangePinName("C107", 2, "2")
ChangePinName("C107", 1, "1")
ElementList(Need,"C106","rcy(100,bar)","0.1uF")
ElementSetAttr("C106","device","CAPACITOR")
ElementSetAttr("C106","manufacturer","unknown")
ElementSetAttr("C106","manufacturer_part_number","unknown")
ElementSetAttr("C106","vendor","unknown")
ElementSetAttr("C106","vendor_part_number","unknown")
ChangePinName("C106", 2, "2")
ChangePinName("C106", 1, "1")
ElementList(Need,"C105","rcy(100,bar)","0.1uF")
ElementSetAttr("C105","device","CAPACITOR")
ElementSetAttr("C105","manufacturer","unknown")
ElementSetAttr("C105","manufacturer_part_number","unknown")
ElementSetAttr("C105","vendor","unknown")
ElementSetAttr("C105","vendor_part_number","unknown")
ChangePinName("C105", 2, "2")
ChangePinName("C105", 1, "1")
ElementList(Need,"C104","rcy(100,bar)","0.1uF")
ElementSetAttr("C104","device","CAPACITOR")
ElementSetAttr("C104","manufacturer","unknown")
ElementSetAttr("C104","manufacturer_part_number","unknown")
ElementSetAttr("C104","vendor","unknown")
ElementSetAttr("C104","vendor_part_number","unknown")
ChangePinName("C104", 2, "2")
ChangePinName("C104", 1, "1")
ElementList(Need,"TP18","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP18","device","TESTPOINT")
ElementSetAttr("TP18","manufacturer","unknown")
ElementSetAttr("TP18","manufacturer_part_number","unknown")
ElementSetAttr("TP18","vendor","unknown")
ElementSetAttr("TP18","vendor_part_number","unknown")
ChangePinName("TP18", 1, "1")
ElementList(Need,"TP16","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP16","device","TESTPOINT")
ElementSetAttr("TP16","manufacturer","unknown")
ElementSetAttr("TP16","manufacturer_part_number","unknown")
ElementSetAttr("TP16","vendor","unknown")
ElementSetAttr("TP16","vendor_part_number","unknown")
ChangePinName("TP16", 1, "1")
ElementList(Need,"TP15","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP15","device","TESTPOINT")
ElementSetAttr("TP15","manufacturer","unknown")
ElementSetAttr("TP15","manufacturer_part_number","unknown")
ElementSetAttr("TP15","vendor","unknown")
ElementSetAttr("TP15","vendor_part_number","unknown")
ChangePinName("TP15", 1, "1")
ElementList(Need,"TP14","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP14","device","TESTPOINT")
ElementSetAttr("TP14","manufacturer","unknown")
ElementSetAttr("TP14","manufacturer_part_number","unknown")
ElementSetAttr("TP14","vendor","unknown")
ElementSetAttr("TP14","vendor_part_number","unknown")
ChangePinName("TP14", 1, "1")
ElementList(Need,"TP13","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP13","device","TESTPOINT")
ElementSetAttr("TP13","manufacturer","unknown")
ElementSetAttr("TP13","manufacturer_part_number","unknown")
ElementSetAttr("TP13","vendor","unknown")
ElementSetAttr("TP13","vendor_part_number","unknown")
ChangePinName("TP13", 1, "1")
ElementList(Need,"TP12","S1751-46R.fp","S1751-46R")
ElementSetAttr("TP12","device","TESTPOINT")
ElementSetAttr("TP12","manufacturer","unknown")
ElementSetAttr("TP12","manufacturer_part_number","unknown")
ElementSetAttr("TP12","vendor","unknown")
ElementSetAttr("TP12","vendor_part_number","unknown")
ChangePinName("TP12", 1, "1")
ElementList(Need,"C1001","RCY100","0.1uF")
ElementSetAttr("C1001","device","CAPACITOR")
ElementSetAttr("C1001","manufacturer","unknown")
ElementSetAttr("C1001","manufacturer_part_number","unknown")
ElementSetAttr("C1001","vendor","unknown")
ElementSetAttr("C1001","vendor_part_number","unknown")
ChangePinName("C1001", 2, "2")
ChangePinName("C1001", 1, "1")
ElementList(Need,"C1000","RCY100","0.1uF")
ElementSetAttr("C1000","device","CAPACITOR")
ElementSetAttr("C1000","manufacturer","unknown")
ElementSetAttr("C1000","manufacturer_part_number","unknown")
ElementSetAttr("C1000","vendor","unknown")
ElementSetAttr("C1000","vendor_part_number","unknown")
ChangePinName("C1000", 2, "2")
ChangePinName("C1000", 1, "1")
ElementList(Need,"TP11","JUMPER1","Reserved for Chassis Connection")
ElementSetAttr("TP11","device","TESTPOINT")
ElementSetAttr("TP11","manufacturer","unknown")
ElementSetAttr("TP11","manufacturer_part_number","unknown")
ElementSetAttr("TP11","vendor","unknown")
ElementSetAttr("TP11","vendor_part_number","unknown")
ChangePinName("TP11", 1, "1")
ElementList(Need,"CONN5","molex-22-23-2091-mini_9_vert.fp","126-220")
ElementSetAttr("CONN5","device","CONNECTOR_9")
ElementSetAttr("CONN5","manufacturer","unknown")
ElementSetAttr("CONN5","manufacturer_part_number","unknown")
ElementSetAttr("CONN5","vendor","unknown")
ElementSetAttr("CONN5","vendor_part_number","unknown")
ChangePinName("CONN5", 9, "9")
ChangePinName("CONN5", 7, "7")
ChangePinName("CONN5", 5, "5")
ChangePinName("CONN5", 3, "3")
ChangePinName("CONN5", 1, "1")
ChangePinName("CONN5", 8, "8")
ChangePinName("CONN5", 6, "6")
ChangePinName("CONN5", 4, "4")
ChangePinName("CONN5", 2, "2")
ElementList(Need,"CONN4","molex-22-23-2091-mini_9_vert.fp","126-221")
ElementSetAttr("CONN4","device","CONNECTOR_9")
ElementSetAttr("CONN4","manufacturer","unknown")
ElementSetAttr("CONN4","manufacturer_part_number","unknown")
ElementSetAttr("CONN4","vendor","unknown")
ElementSetAttr("CONN4","vendor_part_number","unknown")
ChangePinName("CONN4", 9, "9")
ChangePinName("CONN4", 7, "7")
ChangePinName("CONN4", 5, "5")
ChangePinName("CONN4", 3, "3")
ChangePinName("CONN4", 1, "1")
ChangePinName("CONN4", 8, "8")
ChangePinName("CONN4", 6, "6")
ChangePinName("CONN4", 4, "4")
ChangePinName("CONN4", 2, "2")
ElementList(Done)
